repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          [
            "feat",
            "fix",
            "build",
            "chore",
            "ci",
            "debug",
            "docs",
            "perf",
            "refactor",
            "revert",
            "style",
            "test",
          ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.1
    hooks:
      - id: no-commit-to-branch
        name: branch naming convention
        args: ["--pattern", '^(?!((feature|bugfix)\/[a-z0-9-]+|main)$).*']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-case-conflict
      - id: check-ast
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: "24.4.2"
    hooks:
      - id: black
        name: black
        language_version: python3
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint src/
        language: system
        types: [python]
        require_serial: true
      - id: pytest
        name: pytest
        entry: python -m pytest src/api/
        language: system
        types: [python]
        pass_filenames: false
        require_serial: true
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.4
    hooks:
      - id: bandit
        name: bandit
        args: ["--skip", "B101", "-r", "./src/"]
